// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqqxrjjxanahgazxajxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcXhyamp4YW5haGdhenhhanhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTY0MzgsImV4cCI6MjA2MjQzMjQzOH0.zhTJoMxSyowUThGRgWupAU6Y8C3raErz3oXcW3t0b38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);